### ISSUE TITLE
Inconsistency in rotational diffusion.

### ISSUE THREAD

**Issue by murrellb** [MurrellGroup/Diffusions.jl#12]
The refactor aims to hide the state structs from the user, which is good. However, for rotational diffusion, they are not hidden. For example, this is what sampleforward looks like:
```julia
function sampleforward(rng::AbstractRNG, process::RotDiffusionProcess, t::Real, x)
    x_t = MultiRotationState(size(x.rots)...)
    for i in eachindex(x.rots)
        x_t.rots[i] = rotation_diffuse(rng, x.rots[i], t * process.rate)
    end
    return x_t
end
```
returning a MultiRotationState. It also takes a MultiRotationState. It seems like it would be more consistent with the other cases to just decide that rotations will be passed in as `Array{QuatRotation}` and then deal with that directly?

**Comment by bicycle1885** [comment]
Yes, taking and returning an array of `QuatRotation`s looks a better interface.
