### ISSUE TITLE
UniformDiscreteDiffusion issues.

### ISSUE THREAD

**Issue by murrellb** [MurrellGroup/Diffusions.jl#47]
With the last week's changes:
1) I run into a method ambiguity trying to use UniformDiscreteDiffusion with masking:
![image](https://github.com/MurrellGroup/Diffusions.jl/assets/1152087/f1b8e6a3-ebf0-45aa-beab-64bac60e9f57)
2) The standard loss, again for UniformDiscreteDiffusion (but I suspect the issue might be more general) gives NaN gradients when I run it with i) a mask, where some positions are actually masked out, and ii) with the diffusion amount (ie. t) passed in as a vector, where undiffused positions have t=0. Note, the loss is finite (so it isn't a 0/0 issue) but the gradients break! The issue is still present if I add a very small epsilon to the diffusion times, but goes away when that epsilon is large enough. My first guess is that the mask is somehow not respected for the `t` vector during autodiff - so `t=0` (or close to it) are being matched up with positions that were actually masked, and this is blowing up because of the way we scale the loss by `t`.

**Comment by bicycle1885** [comment]
These should have been fixed by #49 and #50.
